// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppkpllsdwfctxtvjxdmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwa3BsbHNkd2ZjdHh0dmp4ZG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTg3NDUsImV4cCI6MjA3MDU3NDc0NX0.fPEpvgac41vrSGa3-FFoe6NaNYmruUa6N1fO5znntPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});